# TRMT Configuration Options
# Lower numbers = Faster trail formation. Higher numbers = Slower trail formation.
erosion-speed:
  min: 15.0
  max: 45.0

# De-erosion (Trail Inactivity Healing Mechanics)
deerosion:
  inactivity-days: 3.0

# Dynamic Step Modifiers (Multipliers applied to base step weights)
modifiers:
  riding-mount: 2.0
  leading-mob: 1.5
  
  # Vegetation Durability Scale
  # 0.2 means plants/leaves have only 20% of the threshold of a normal block
  # (e.g. if a ground path takes 30 steps, a bush will vanish in just 6 steps!)
  vegetation-durability-factor: 0.2

  boots:
    leather: 0.8
    gold: 1.0
    chainmail: 1.1
    iron: 1.3
    diamond: 1.4
    netherite: 1.6
    none: 0.5

  feather-falling-reduction-per-level: 0.15
