name: Automated Plugin Compiler

on:
  push:
    branches: [ "main" ] # Fires every time you update your code
  workflow_dispatch:      # Allows you to click a button and build manually at any time

jobs:
  compile-plugin:
    runs-on: ubuntu-latest

    steps:
    - name: Get Code From Repository
      uses: actions/checkout@v4

    - name: Initialize Java Development Kit 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Maven Compile Engine
      # Runs the package command inside our specific /spigot directory
      run: mvn clean package --file spigot/pom.xml

    - name: Export Compiled Jar File For Download
      uses: actions/upload-artifact@v4
      with:
        name: TRMT-Plugin-Build
        path: spigot/target/*.jar
        
